version: '3.5'

services:
  qdrant: 
    image: qdrant/qdrant
    ports:
      - 6333:6333
    volumes:
      - /home/azureuser/qdrant:/qdrant/storage

  jupyter:
    container_name: jupyter-nb
    image: saurabh103/jupyter-notebook
    build: .
    depends_on:
      - "qdrant"
    ports:
      - 80:8888
    volumes:
      - .:/home/jovyan
    environment:
      - NB_UID=1001
      - NB_GID=100
      - JUPYTER_TOKEN=daredevil@09

networks:
  default:
    name: main
          
  

